eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flydb?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true




